global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
    cluster: test

rule_files:
  - ssl_expiry.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node-exporter:9100']
      labels:
        group: 'production'

    metric_relabel_configs:
    - source_labels: [instance]
      regex: '(node-exporter):9100'
      replacement: '$1'
      target_label: 'my_new_label'

    relabel_configs:    
    - source_labels: [__address__]
      regex: '(.*)'
      replacement: '$1'
      target_label: 'my_address'


  - job_name: 'blackbox-cert-check'
    metrics_path: /probe
    params:
      module: [cert_check]
    scrape_interval: 10s
    scrape_timeout: 10s
    
    static_configs:
      - targets:
        - https://tvstack.dentsuaegis.com
        - https://admin.tvstack.dentsuaegis.com
    
    dns_sd_configs:  
      - names:
        - 'gitea-instances.az.globaldevops.gdpdentsu.net'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [instance]
        regex: '(gitea-tooling)(.*):443'
        target_label: __param_target
        replacement:   'https://$1$2'
      - source_labels: [__param_target]
        target_label: instance

  - job_name: 'blackbox-gitea-regex'
    metrics_path: /probe
    params:
      module: [gitea_regex]
    scrape_interval: 10s
    scrape_timeout: 10s
    
    dns_sd_configs:  
      - names:
        - 'gitea-instances.az.globaldevops.gdpdentsu.net'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [instance]
        regex: '(gitea-tooling)(.*):443'
        target_label: __param_target
        replacement:   'https://$1$2'
      - source_labels: [__param_target]
        target_label: instance
  
  
  #- job_name: 'dns-sd-testing'
  #  dns_sd_configs:  
  #  - names:
  #    - 'gitea.az.globaldevops.gdpdentsu.net'
      
    #relabel_configs:
    #- source_labels: ['__meta_dns_name']
    #  regex:         'telemetry\.(.+?)\..+?\.srv\.example\.org'
    #  target_label:  'zone'
    #  replacement:   '$1'


#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
      # - alertmanager:9093

#rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
