apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
