version: '3'
services:
  #######################
  # First stack
  #######################
  prom-server:
    build: ./server
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:latest

  blackbox-exporter:
    build: ./blackbox
    ports:
      - "9115:9115"
    entrypoint:
    - /bin/blackbox_exporter
    - --config.file=/etc/blackbox_exporter/config.yml
    - --log.level=debug

  grafana:
    image: grafana/grafana
    depends_on:
      - prom-server
    ports:
      - 4000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboard-providers:/etc/grafana/provisioning/dashboards/
      - ./grafana/dashboards:/var/lib/grafana/dashboards/

  #######################
  # Second stack
  #######################
  prom-server2:
    build: ./server2
    ports:
      - "9091:9090"
  
  grafana2:
    image: grafana/grafana
    depends_on:
      - prom-server2
    ports:
      - 4001:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources2/
      #- ./grafana/dashboard-providers:/etc/grafana/provisioning/dashboards2/
      #- ./grafana/dashboards:/var/lib/grafana/dashboards/
  