version: '3'
services:
  #######################
  #  master
  #######################
  prom-server-master:
    build: ./master/server
    ports:
      - "2000:9090"


  #######################
  # Sub001
  #######################
  prom-server-sub001:
    build: ./sub001/server
    ports:
      - "3000:9090"
  
  node-exporter-sub001:
    image: prom/node-exporter:latest

  blackbox-exporter-sub001:
    build: ./sub001/blackbox
    ports:
      - "3010:9115"
    entrypoint:
    - /bin/blackbox_exporter
    - --config.file=/etc/blackbox_exporter/config.yml
    - --log.level=debug

  grafana-sub001:
    image: grafana/grafana
    depends_on:
      - prom-server-sub001
    ports:
      - 3020:3000
    volumes:
      - ./sub001/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./sub001/grafana/dashboard-providers:/etc/grafana/provisioning/dashboards/
      - ./sub001/dashboards:/var/lib/grafana/dashboards/
