adminUser: admin
adminPassword: admin

datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true

dashboardProviders: 
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards


dashboards:
  default:
    some-dashboard:
      json: |
        {
          "annotations": {
              "list": [
              {
                  "builtIn": 1,
                  "datasource": "-- Grafana --",
                  "enable": true,
                  "hide": true,
                  "iconColor": "rgba(0, 211, 255, 1)",
                  "name": "Annotations & Alerts",
                  "type": "dashboard"
              }
              ]
          },
          "editable": true,
          "gnetId": null,
          "graphTooltip": 0,
          "id": 11,
          "links": [],
          "panels": [
              {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "fill": 1,
              "gridPos": {
                  "h": 16,
                  "w": 24,
                  "x": 0,
                  "y": 0
              },
              "id": 2,
              "legend": {
                  "alignAsTable": true,
                  "avg": false,
                  "current": false,
                  "max": false,
                  "min": false,
                  "rightSide": true,
                  "show": true,
                  "total": false,
                  "values": false
              },
              "lines": true,
              "linewidth": 1,
              "links": [],
              "nullPointMode": "null",
              "percentage": false,
              "pointradius": 5,
              "points": false,
              "renderer": "flot",
              "seriesOverrides": [],
              "spaceLength": 10,
              "stack": false,
              "steppedLine": false,
              "targets": [
                  {
                  "$$hashKey": "object:3198",
                  "expr": "ALERTS{alertstate=~\"pending|firing\"}",
                  "format": "time_series",
                  "intervalFactor": 1,
                  "legendFormat": "{{alertname}}-{{severity}}",
                  "refId": "A"
                  }
              ],
              "thresholds": [],
              "timeFrom": null,
              "timeShift": null,
              "title": "Prometheus Alerts",
              "tooltip": {
                  "shared": true,
                  "sort": 0,
                  "value_type": "individual"
              },
              "type": "graph",
              "xaxis": {
                  "buckets": null,
                  "mode": "time",
                  "name": null,
                  "show": true,
                  "values": []
              },
              "yaxes": [
                  {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                  },
                  {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                  }
              ],
              "yaxis": {
                  "align": false,
                  "alignLevel": null
              }
              }
          ],
          "schemaVersion": 16,
          "style": "dark",
          "tags": [],
          "templating": {
              "list": []
          },
          "time": {
              "from": "now-6h",
              "to": "now"
          },
          "timepicker": {
              "refresh_intervals": [
              "5s",
              "10s",
              "30s",
              "1m",
              "5m",
              "15m",
              "30m",
              "1h",
              "2h",
              "1d"
              ],
              "time_options": [
              "5m",
              "15m",
              "1h",
              "6h",
              "12h",
              "24h",
              "2d",
              "7d",
              "30d"
              ]
          },
          "timezone": "",
          "title": "Prometheus Alerts",
          "uid": "z6zVVuhmz",
          "version": 1
        }

