modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      fail_if_not_matches_regexp:
        - "Hello World"
      preferred_ip_protocol: "ip4"
      valid_http_versions:
        - "HTTP/1.1" 
        - "HTTP/2"
      method: GET
      tls_config:
        insecure_skip_verify: true
