global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  #- job_name: 'prometheus'
  #  static_configs:
  #  - targets: ['prom-server-master:9090']


  - job_name: 'metrics_from_other_prom_servers'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="blackbox-cert-check"}'
        #- '{__name__=~"job:.*"}'

    static_configs:
    - targets: ['prom-server-sub001:9090']
  